/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   user-profile-dialog.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

declare class EtoolsUserProfileDialog extends LitElement {
  profile: object | null | undefined;

  /**
   * users: Array,
   */
  availableCountryIds: any[] | null | undefined;
  availableGroups: any[] | null | undefined;
  showEmail: boolean;
  openUserProfileDialog(): void;
  _closeUserProfileDialog(e: any): void;
  _mapIds(profile: any): void;
  saveData(): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-user-profile-dialog": EtoolsUserProfileDialog;
  }
}
